name: harcapp_core
description: A new Flutter package project.
version: 0.0.1
homepage: harcapp.web.app

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  assets_audio_player: ^3.1.0
  auto_size_text: ^3.0.0
  connectivity_plus: ^6.0.1
  decorated_icon: ^1.2.1
  fluttertoast: ^8.2.2
  flutter_feather_icons: ^2.0.0+1
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.10+1
  flutter_widget_from_html: ^0.14.9
  htmltopdfwidgets: ^1.0.3
  implicitly_animated_reorderable_list_2: ^0.5.1
  linked_scroll_controller: ^0.2.0
  logger: ^2.0.2+1
  material_design_icons_flutter: ^7.0.7296
  mime: 1.0.5
  native_device_orientation: ^2.0.3
  oktoast: ^3.3.1
  open_filex: ^4.4.0
  pdf: ^3.8.1
  printing: ^5.9.1
  provider: ^6.0.5
  tuple: ^2.0.2
  url_launcher: ^6.1.11
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  assets:

    - assets/images/meto/

    - assets/forms/
    - assets/gawedy/
    - assets/konspekty/
    - assets/konspekty/beretowa/
    - assets/konspekty/bibliodrama/
    - assets/konspekty/biwak_bez_nadzoru/
    - assets/konspekty/budowanie_kapliczki/
    - assets/konspekty/budowanie_szopki_bozonarodzeniowej/
    - assets/konspekty/druzynowe_mycie_w_jeziorze/
    - assets/konspekty/ekstremalna_droga_krzyzowa/
    - assets/konspekty/gang_potencjalnych_porywaczy/
    - assets/konspekty/gaweda_o_swietym/
    - assets/konspekty/ignacjanski_rachunek_sumienia/
    - assets/konspekty/kadrowe_msze/
    - assets/konspekty/kalambury_z_prawa_harcerskiego/
    - assets/konspekty/kalambury_z_prawa_zucha/
    - assets/konspekty/kilkutygodniowe_obozowanie_w_lesie/
    - assets/konspekty/koledowanie_z_quizem_interpretacyjnym/
    - assets/konspekty/kontrowersyjna_dyskusja/
    - assets/konspekty/modlitwa_przed_posilkiem/
    - assets/konspekty/musztra_i_dbalosc_o_umundurowanie/
    - assets/konspekty/negocjowanie_koalicji_wlasnych_partii_politycznych/
    - assets/konspekty/nocne_podkradanie/
    - assets/konspekty/opieka_nad_roslinka/
    - assets/konspekty/opowiedzenie_gawedy_o_autorytecie/
    - assets/konspekty/padnij_za_zbyt_wolno_wykonana_zbiorke/
    - assets/konspekty/pielgrzymka_druzyny/
    - assets/konspekty/post/
    - assets/konspekty/pozno_zyciowe_rozmowy/
    - assets/konspekty/rowerowe_nabozenstwo_majowe/
    - assets/konspekty/refleksja_nad_aksjomatem_ducha/
    - assets/konspekty/rozpoczynanie_posilku_wspolnym_spiewaniem/
    - assets/konspekty/sad_nad_postawa/
    - assets/konspekty/savoir_vivre_urzadzen_mobilnych/
    - assets/konspekty/spiewogranie_z_quizem_interpretacyjnym/
    - assets/konspekty/staly_spowiednik/
    - assets/konspekty/sznury_funkcje_stopnie/
    - assets/konspekty/warta_nocna/
    - assets/konspekty/wedrowka/
    - assets/konspekty/wedrowka_bez_zasobow/
    - assets/konspekty/wedrowka_medytacyjna/
    - assets/konspekty/wieczorne_przeprosiny_i_podziekowania/
    - assets/konspekty/wlasny_nagrobek/
    - assets/konspekty/wspolna_minuta_czosnku/
    - assets/konspekty/zagadki_matematyczno_logiczne/
    - assets/konspekty/zakwaterowanie_pod_namiotem/
    - assets/konspekty/zimowiskowe_apele_przed_osrodkiem/
    - assets/konspekty/zwiad_lokalnej_spolecznosci/
    - assets/wiersze/