name: harcapp_core
description: A new Flutter package project.
version: 0.0.1
homepage: harcapp.web.app

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # assets_audio_player: ^3.1.1
  auto_size_text: ^3.0.0
  cached_network_image: ^3.3.1
  connectivity_plus: ^6.1.2
  decorated_icon: ^1.2.1
  dio: ^5.8.0+1
  fluttertoast: ^8.2.10
  flutter_feather_icons: ^2.0.0+1
  flutter_layout_grid: 2.0.7
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.17
  flutter_widget_from_html: ^0.15.3
  html_pdf_widgets: ^0.0.2
  html_unescape: ^2.0.0
  implicitly_animated_reorderable_list_2: ^0.6.0
  just_audio: ^0.9.46
  linked_scroll_controller: ^0.2.0
  logger: ^2.5.0
  material_design_icons_flutter: ^7.0.7296
  mime: ^2.0.0
  native_device_orientation: ^2.0.3
  oktoast: ^3.4.0
  # open_filex: ^4.6.0  # Because of this bug https://github.com/javaherisaber/open_filex/pull/19
  open_filex:
    git:
      url: https://github.com/mufassalhussain/open_filex
  pdf: ^3.11.2
  printing: ^5.14.0
  provider: ^6.1.2
  semaphore_plus: ^0.3.1
  shared_preferences: ^2.5.1
  tuple: ^2.0.2
  url_launcher: ^6.3.1
  uuid: ^3.0.7
  webfeed_plus: ^1.1.2
  youtube_player_flutter: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:

    - assets/images/meto/

    - assets/forms/
    - assets/gawedy/
    - assets/konspekty/

    - assets/konspekty/common/
    - assets/konspekty/common/warsztaty_duchowe/

    - assets/konspekty/harcerskie/
    - assets/konspekty/harcerskie/beretowa/
    - assets/konspekty/harcerskie/bibliodrama/
    - assets/konspekty/harcerskie/biwak_bez_nadzoru/
    - assets/konspekty/harcerskie/budowanie_kapliczki/
    - assets/konspekty/harcerskie/budowanie_szopki_bozonarodzeniowej/
    - assets/konspekty/harcerskie/druzynowe_mycie_w_jeziorze/
    - assets/konspekty/harcerskie/druzynowe_przekazanie_bsp/
    - assets/konspekty/harcerskie/dwie_roty_dwoch_przyrzeczen_harcerskich/
    - assets/konspekty/harcerskie/ekstremalna_droga_krzyzowa/
    - assets/konspekty/harcerskie/gang_potencjalnych_porywaczy/
    - assets/konspekty/harcerskie/gaweda_o_swietym/
    - assets/konspekty/harcerskie/ignacjanski_rachunek_sumienia/
    - assets/konspekty/harcerskie/kadrowe_msze/
    - assets/konspekty/harcerskie/kalambury_z_prawa_harcerskiego/
    - assets/konspekty/harcerskie/kalambury_z_prawa_zucha/
    - assets/konspekty/harcerskie/kilkutygodniowe_obozowanie_w_lesie/
    - assets/konspekty/harcerskie/koledowanie_z_quizem_interpretacyjnym/
    - assets/konspekty/harcerskie/kontrowersyjna_dyskusja/
    - assets/konspekty/harcerskie/modlitwa_przed_posilkiem/
    - assets/konspekty/harcerskie/msza_obozowa_lecz_nie_tylko/
    - assets/konspekty/harcerskie/musztra_i_dbalosc_o_umundurowanie/
    - assets/konspekty/harcerskie/negocjowanie_koalicji_wlasnych_partii_politycznych/
    - assets/konspekty/harcerskie/nocne_podkradanie/
    - assets/konspekty/harcerskie/opieka_nad_roslinka/
    - assets/konspekty/harcerskie/opowiedzenie_gawedy_o_autorytecie/
    - assets/konspekty/harcerskie/padnij_za_zbyt_wolno_wykonana_zbiorke/
    - assets/konspekty/harcerskie/pielgrzymka_druzyny/
    - assets/konspekty/harcerskie/podzial_pirackiego_lupu/
    - assets/konspekty/harcerskie/post/
    - assets/konspekty/harcerskie/pozno_zyciowe_rozmowy/
    - assets/konspekty/harcerskie/rowerowe_nabozenstwo_majowe/
    - assets/konspekty/harcerskie/refleksja_nad_aksjomatem_ducha/
    - assets/konspekty/harcerskie/rozpoczynanie_posilku_wspolnym_spiewaniem/
    - assets/konspekty/harcerskie/sad_nad_postawa/
    - assets/konspekty/harcerskie/savoir_vivre_urzadzen_mobilnych/
    - assets/konspekty/harcerskie/spiewogranie_z_quizem_interpretacyjnym/
    - assets/konspekty/harcerskie/swieczka_prawa_harcerskiego/
    - assets/konspekty/harcerskie/swieczka_prawa_zuchowego/
    - assets/konspekty/harcerskie/staly_spowiednik/
    - assets/konspekty/harcerskie/sznury_funkcje_stopnie/
    - assets/konspekty/harcerskie/warta_nocna/
    - assets/konspekty/harcerskie/wedrowka/
    - assets/konspekty/harcerskie/wedrowka_bez_zasobow/
    - assets/konspekty/harcerskie/wedrowka_medytacyjna/
    - assets/konspekty/harcerskie/wieczorne_przeprosiny_i_podziekowania/
    - assets/konspekty/harcerskie/wlasny_nagrobek/
    - assets/konspekty/harcerskie/wspolna_minuta_czosnku/
    - assets/konspekty/harcerskie/zagadki_matematyczno_logiczne/
    - assets/konspekty/harcerskie/zakwaterowanie_pod_namiotem/
    - assets/konspekty/harcerskie/zimowiskowe_apele_przed_osrodkiem/
    - assets/konspekty/harcerskie/zwiad_lokalnej_spolecznosci/
    - assets/konspekty/harcerskie/zycie_i_swiat_prl/

    - assets/konspekty/ksztalcenie/
    - assets/konspekty/ksztalcenie/czynniki_i_mechanizmy_ksztaltowania_duchowosci/
    - assets/konspekty/ksztalcenie/dwie_roty_dwoch_przyrzeczen_harcerskich/
    - assets/konspekty/ksztalcenie/warsztaty_wychowania_duchowego/
    - assets/konspekty/ksztalcenie/warsztaty_wychowania_duchowego_old/
    - assets/konspekty/ksztalcenie/wstep_do_wychowania_duchowego/

    - assets/poradnik/czynniki_i_mechanizmy_ksztaltowania_duchowosci/
    - assets/poradnik/dwie_roty_dwoch_przyrzeczen_harcerskich/
    - assets/poradnik/o_strukturze_duchowosci/

    - assets/wiersze/

    - fonts/
    - fonts/Lato/
    - fonts/Lato/Lato-Regular.ttf
    - fonts/Lato/Lato-Italic.ttf
    - fonts/Lato/Lato-Bold.ttf
    - fonts/Lato/Lato-BoldItalic.ttf

  fonts:

    - family: Lato
      fonts:
        - asset: fonts/Lato/Lato-Regular.ttf
          weight: 300
        - asset: fonts/Lato/Lato-Italic.ttf
          weight: 300
          style: italic
        - asset: fonts/Lato/Lato-Bold.ttf
          weight: 700
        - asset: fonts/Lato/Lato-BoldItalic.ttf
          weight: 700
          style: italic

    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu/Ubuntu-B.ttf
          weight: 900
        - asset: fonts/Ubuntu/Ubuntu-BI.ttf
          weight: 900
          style: italic
        - asset: fonts/Ubuntu/Ubuntu-M.ttf
          weight: 700
        - asset: fonts/Ubuntu/Ubuntu-MI.ttf
          weight: 700
          style: italic
        - asset: fonts/Ubuntu/Ubuntu-R.ttf
          weight: 500
        - asset: fonts/Ubuntu/Ubuntu-RI.ttf
          weight: 500
          style: italic
        - asset: fonts/Ubuntu/Ubuntu-L.ttf
          weight: 300
        - asset: fonts/Ubuntu/Ubuntu-LI.ttf
          weight: 300
          style: italic
        - asset: fonts/Ubuntu/Ubuntu-Th.ttf
          weight: 100