name: piosenkomat
description: Piosenkomat, automat przesiewający mejle z piosenkami na harcapp@gmail.com.
publish_to: none

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  args: ^2.6.0
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  harcapp_core:
    path: ../..
  http: ^1.2.2
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.25.0

flutter:
  uses-material-design: true
